// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfH9t_jxE8yx0NOUKz2GJp0HTah2kZKGw',
    appId: '1:169707855355:web:48c17bae77add5e54fff5e',
    messagingSenderId: '169707855355',
    projectId: 'musicplayer-eec88',
    authDomain: 'musicplayer-eec88.firebaseapp.com',
    storageBucket: 'musicplayer-eec88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd7wNlZ1njEpqx3nsCOPeN_o_jlU8Ryjw',
    appId: '1:169707855355:android:431af1580ea75f8b4fff5e',
    messagingSenderId: '169707855355',
    projectId: 'musicplayer-eec88',
    storageBucket: 'musicplayer-eec88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG9x0HXXVyoQixuFZcrn1pGzV6baTmiSI',
    appId: '1:169707855355:ios:6aaa5e137da615024fff5e',
    messagingSenderId: '169707855355',
    projectId: 'musicplayer-eec88',
    storageBucket: 'musicplayer-eec88.appspot.com',
    iosBundleId: 'com.example.groovex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG9x0HXXVyoQixuFZcrn1pGzV6baTmiSI',
    appId: '1:169707855355:ios:2adde9589e8a7a694fff5e',
    messagingSenderId: '169707855355',
    projectId: 'musicplayer-eec88',
    storageBucket: 'musicplayer-eec88.appspot.com',
    iosBundleId: 'com.example.groovex.RunnerTests',
  );
}
