// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVnqonB5-9PHwGrocX4EpgVF7YHiDUAn4',
    appId: '1:148657030728:web:7297da6c3ba0462c65ba7d',
    messagingSenderId: '148657030728',
    projectId: 'groovex-43cd5',
    authDomain: 'groovex-43cd5.firebaseapp.com',
    storageBucket: 'groovex-43cd5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaB1rLmzbsk5e4Ax49IMBLiB2MkkZgQ2w',
    appId: '1:148657030728:android:3f300931ed1d838e65ba7d',
    messagingSenderId: '148657030728',
    projectId: 'groovex-43cd5',
    storageBucket: 'groovex-43cd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm_6jMI4lENZB01BkavHOLUwWguZfZWeQ',
    appId: '1:148657030728:ios:024db7f5073c867e65ba7d',
    messagingSenderId: '148657030728',
    projectId: 'groovex-43cd5',
    storageBucket: 'groovex-43cd5.appspot.com',
    iosBundleId: 'com.example.groovex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm_6jMI4lENZB01BkavHOLUwWguZfZWeQ',
    appId: '1:148657030728:ios:a727fb0fbc4c6fe465ba7d',
    messagingSenderId: '148657030728',
    projectId: 'groovex-43cd5',
    storageBucket: 'groovex-43cd5.appspot.com',
    iosBundleId: 'com.example.groovex.RunnerTests',
  );
}
